### ISSUE TITLE
More file types (Typescript) and potential for scaffolding more files

### ISSUE THREAD

**Issue by jgarplind** [joshwcomeau/new-component#16]
Hey, first of all, thanks for open sourcing this!

I got curious about it, but the first "blocker" is that I typically work in `.tsx`-files and it would be great to scaffold those from scratch. Would you be interested in a PR that adds a flag for Typescript, or would I be better off forking than bloating a JS-centered tool? (1)

Further, most of my work happens in a redux context, so it would be cool to be able to optionally spin up a `componentname.reducer.fileending` as well as a (we are nearing very opinionated territory here) `componentname.container.fileending`. (2)

Finally, I typically work in a SCSS modules context, so the ability to scaffold a `(.module.).(s)css`-file would be nice as well! But again, this might be beyond the scope of this repo and its better off as a fork. (3)

Happy to look into implementing any of the above based on my availability and your preferences.

**Comment by eric-burel** [comment]
Hi, a great use case that needs more file to the boilerplate is generating a Storybook story + the corresponding Jest unit test. 
This is my structure usually like this: https://github.com/VulcanJS/vulcan-next/tree/devel/src/components/home (and these days I even put the story into "tests" folder instead of isolating it, because I consider it a visual test).
